# Pràctica 1 - El procés de l'aprenentatge automàtic:
## Imports

In [1]:
import os
from sklearn.calibration import LabelEncoder
from sklearn.discriminant_analysis import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from skimage import io
from skimage.transform import resize
from skimage.color import rgb2gray
import numpy as np

## Funció de processament de dades

In [2]:
def load_and_preprocess(folder_path, target_size=(64, 64)):
    images = []
    labels = []
    
    for label in os.listdir(folder_path):
        label_path = os.path.join(folder_path, label)
        
        for image_name in os.listdir(label_path):
            image_path = os.path.join(label_path, image_name)
            image = io.imread(image_path)
            
            # Preprocess the image (resize, convert to grayscale, etc.)
            image = resize(image, target_size)
            # Check if the image is already grayscale
            if image.ndim == 2:
                # Grayscale image
                images.append(image.flatten())
            else:
                # Convert color image to grayscale
                gray_image = rgb2gray(image)
                images.append(gray_image.flatten())

            labels.append(label)
    
    return np.array(images), np.array(labels)

## Processament de dades

In [3]:
train_path = 'dat/train/'
test_path = 'dat/test/'
X_train, y_train = load_and_preprocess(train_path)
print("Imatges train processades")
X_test, y_test = load_and_preprocess(test_path)
print("Imatges test processades")

Imatges train processades
Imatges test processades


## Transformació de les dades

In [4]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.fit_transform(y_test)
print("Imatges escalades")

Imatges escalades


## Entrenament i test dels SVM

### Kernel Lineal

In [6]:
print("KERNEL LINEAL")
svm = SVC(kernel='linear')
svm.fit(X_train_scaled, y_train)
y_pred = svm.predict(X_test_scaled)

# Evaluate the Model
cf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion matrix:\n", cf_matrix)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

KERNEL LINEAL
Confusion matrix:
 [[ 18   5  10   2   8   4   9   3   4   7  20   5   8  11   2   0]
 [108  21  42   0  22   1  30   4   7   9   7   5   1   1   2   0]
 [ 35  61  11  18  22   7  15  11   1  21   3   5   4   7   7   0]
 [ 39   6  70   2   4   0  26   4   3   0   2   2   2   0   0   0]
 [ 42  19  22  11  13  13  13   9   3  12  10  26   4  12   2   0]
 [ 25  41  12  28  14   5  27   8   3   8   5  15   8   6   3   0]
 [ 19  10   8   6   7   6   9   2   5   4  12   5   8   5   4   0]
 [ 22  12  26  10   8   5   4   7  11   9  13   7  12  38   5   0]
 [ 18  12  23   8   4   2   2   5   8   8  12   6   9  34   3   0]
 [ 62  34  37   7  29   6  23  10   6  21  20  13   3   1   2   0]
 [ 17   2   4   5   8  47   2   0   1  14   4   6   0   3   2   0]
 [106  23  34  17  16   3  65  10   5   9   3   6   6   4   3   0]
 [ 33  27  10  14  21   5  17  13   9  14  15   6  14   8   9   0]
 [ 25  11   8   6   4   2  16  72  14   6   3   8   3   7   7   0]
 [  6   9   8   4  15   2  12

### Kernel RBF

In [7]:
print("KERNEL RBF")
svm = SVC(kernel='rbf')
svm.fit(X_train_scaled, y_train)
y_pred = svm.predict(X_test_scaled)

# Evaluate the Model
cf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion matrix:\n", cf_matrix)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

KERNEL RBF
Confusion matrix:
 [[  8   5  10   3   3   3   0   2   3   5  34  13  16   6   5   0]
 [ 50  40  62   6  18   4  31   1   5  18   9   4   4   1   7   0]
 [  3 106   8  17   5  11  11   5   4  29   5   7   6   4   7   0]
 [  3  12 112   1   4   2  12   1   5   0   4   2   2   0   0   0]
 [  5  18  16   7   5   7  15   5  13  11  21  58  14   7   9   0]
 [  6  54   8  38   4   4  16   2  13  12   5   7  18   7  14   0]
 [  3  10   6   6   0   7   2   1   4   6  14  10  24   4  13   0]
 [  6   8  12   3   3   8   2   5  11  15  23  18  28  29  18   0]
 [  5   8   9   3   3   6   1   5   9  13  16  14  22  25  15   0]
 [ 21  37  25  15  46  11  17   5   6  21  15  15  17   6  17   0]
 [  2   9   3   2   1  43   0   0   0  16  14  11   6   6   2   0]
 [ 29  63  59  15   8   0  94   3   9   9   3   3   7   3   5   0]
 [  3  29   5  17   2   5   4   6   9  26  20   1  31  14  43   0]
 [  4  13   9   7   3   3  10  92  13   2   5   9   8   3  11   0]
 [  2   5   1   0   2   0   2   

### Kernel Polinomic

In [8]:
print("KERNEL POLINOMIC")
svm = SVC(kernel='poly')
svm.fit(X_train_scaled, y_train)
y_pred = svm.predict(X_test_scaled)

# Evaluate the Model
cf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion matrix:\n", cf_matrix)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)

KERNEL POLINOMIC
Confusion matrix:
 [[ 11   2  54   4   1   0   1   0   1   2  16   2  15   2   5   0]
 [ 35  14 128  20   6   2  21   0   1   6   4   3   7   1  12   0]
 [  5  56  57  42   2   4  12   1   0  21   2   0  13   0  13   0]
 [  4   3 131   5   3   0   7   1   0   1   2   0   2   0   1   0]
 [ 14  12  76  21   0   2  25   0   2  10   6  24  11   3   5   0]
 [  8  18  79  55   2   2  18   2   3   2   0   2  10   0   7   0]
 [  7   1  48  17   0   3   2   0   0   2   2   1  23   1   3   0]
 [ 11   7  78  16   1   4   4   2   0   6   8   0  25  21   6   0]
 [  5   7  64  14   1   2   3   2   0   6   7   0  18  20   5   0]
 [ 25  21  90  29  16   2  21   5   2  19   3   4  16   2  19   0]
 [  5  10  34  13   0  28   0   0   0   8   3   2  10   1   1   0]
 [ 18  12 131  46   4   0  67   1   2   6   0   2   7   0  14   0]
 [  8  13  90  40   2   0   9   0   1  10   3   0  23   0  16   0]
 [  5   5  70  14   0   3  21  58   3   1   2   1   8   0   1   0]
 [  3   8  46  12   0   0 